"""empty message

Revision ID: 1de9f8cd2e43
Revises: 48766b27dfad
Create Date: 2017-05-31 09:57:45.918407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de9f8cd2e43'
down_revision = '48766b27dfad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fragment', sa.Column('approved', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('fragment', sa.Column('date_approved', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fragment') as batch_op:
        batch_op.drop_column('date_approved')
        batch_op.drop_column('approved')
    # ### end Alembic commands ###
