"""empty message

Revision ID: 2541a8bcded6
Revises: 1de9f8cd2e43
Create Date: 2017-06-01 10:31:25.401242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2541a8bcded6'
down_revision = '1de9f8cd2e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poem') as batch_op:
        batch_op.drop_column('fragment_order')
        batch_op.add_column(sa.Column('fragment_order', sa.String(500), nullable=False))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poem') as batch_op:
        batch_op.drop_column('date_created')
        batch_op.drop_column('fragment_order')
        batch_op.add_column(sa.Column('fragment_order', sa.PickleType(), nullable=False))    
    # ### end Alembic commands ###
