"""empty message

Revision ID: 48766b27dfad
Revises: 
Create Date: 2017-05-15 19:52:39.012563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48766b27dfad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fragment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=250), nullable=False),
    sa.Column('date_uploaded', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    op.create_table('poem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fragment_order', sa.PickleType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poems_fragments',
    sa.Column('fragment_id', sa.Integer(), nullable=True),
    sa.Column('poem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fragment_id'], ['fragment.id'], ),
    sa.ForeignKeyConstraint(['poem_id'], ['poem.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poems_fragments')
    op.drop_table('poem')
    op.drop_table('fragment')
    # ### end Alembic commands ###
